
let tagsSBL = {
			WC1_Presion: [
				{tag: "ns=3;s=[PLC_W10]WC1_Presion.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Presion.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Presion.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Presion.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Presion.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC1_Presion.EU", type: "int32"},
			], 
			WC1_Humedad: [
				{tag: "ns=3;s=[PLC_W10]WC1_Humedad.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Humedad.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Humedad.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Humedad.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Humedad.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC1_Humedad.EU", type: "int32"},
			], 
			WC1_Flujo: [
				{tag: "ns=3;s=[PLC_W10]WC1_Flujo.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Flujo.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Flujo.Value", type: "int32"},				
				{tag: "ns=3;s=[PLC_W10]WC1_Flujo.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC1_Flujo.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC1_Flujo.EU", type: "int32"},
			],
			WC2_Temperatura: [
				{tag: "ns=3;s=[PLC_W10]WC2_Temperatura.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC2_Temperatura.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC2_Temperatura.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC2_Temperatura.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC2_Temperatura.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC2_Temperatura.EU", type: "int32"},
			], 
			WC2_Presion: [
				{tag: "ns=3;s=[PLC_W10]WC2_Presion.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC2_Presion.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC2_Presion.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC2_Presion.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC2_Presion.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC2_Presion.EU", type: "int32"},
			],
			WC3_Temperatura: [
				{tag: "ns=3;s=[PLC_W10]WC3_Temperatura.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Temperatura.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Temperatura.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Temperatura.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Temperatura.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC3_Temperatura.EU", type: "int32"},
			], 
			WC3_Presion: [
				{tag: "ns=3;s=[PLC_W10]WC3_Presion.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Presion.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Presion.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Presion.Hightlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC3_Presion.EU", type: "int32"},
			], 
			WC3_Humedad: [
				{tag: "ns=3;s=[PLC_W10]WC3_Humedad.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Humedad.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Humedad.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Humedad.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Humedad.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC3_Humedad.EU", type: "int32"},
			], 
			WC3_Flujo: [
				{tag: "ns=3;s=[PLC_W10]WC3_Flujo.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Flujo.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Flujo.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Flujo.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Flujo.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC3_Flujo.EU", type: "int32"},
			], 
			WC3_Ritmo: [
				{tag: "ns=3;s=[PLC_W10]WC3_Ritmo.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Ritmo.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Ritmo.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Ritmo.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC3_Ritmo.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC3_Ritmo.EU", type: "int32"},
			], 
			WC4_Flujo: [
				{tag: "ns=3;s=[PLC_W10]WC4_Flujo.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC4_Flujo.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC4_Flujo.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC4_Flujo.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC4_Flujo.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC4_Flujo.EU", type: "int32"},
			], 
			WC4_Humedad: [
				{tag: "ns=3;s=[PLC_W10]WC4_Humedad.Idvariable", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC4_Humedad.Dtcaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC4_Humedad.Value", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC4_Humedad.Hightlimit", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]WC4_Humedad.Lowlimit", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]WC4_Humedad.EU", type: "int32"},
			],
			events: [
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Duration", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Idmachine", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Read", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Return", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Type", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Description", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Endtime", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Idevento", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_Event[0].Starttime", type: "int32"},
			],
			oee: [ 
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Idmachine", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Dttimecaptura", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].OEE", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Availability", type: "int32"},
				
				// RunTime
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Read", type: "int32"},
				// Test Data

				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Available", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Performance", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].ICT", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].TotalParts", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Quality", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].GoodParts", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].LoteId", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].ParteId", type: "int32"},
				{tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].ShiftId", type: "int32"},
				
				// {tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Read", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Return", type: "int32"},
				// {tag: "ns=3;s=[PLC_W10]FIFO_WC_OEE[0].Running", type: "int32"},
			]
		};

export { tagsSBL };